# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('Address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('login', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.SignUp')),
            ],
        ),
    ]
